greetin=['hello','hai','watsup','hi','hey there','hey,there']
greetout=["hai,it's good to see you !!!!!!",'hello,how are you',"hai,how's your day"]
bot_call=['you','your','yours']
user_call=['i','me','myself','mine','my']
bot_unknown_questions_himself=["Actually...., I don't know","I am still working on it",
                                       "who cares...but now iam here for you","who knows...."]
user_unknown_questions=["i don't have any idea about you","You haven't told me","how do i know ,we've just met"]
noun_list=['NN','NNS','NNPS']
adverb_list=['RB','RBR','RBS']
verb_list=['VB','VBG','VBD','VBN','VBP','VBZ']
adjective_list=['JJ','JJR','JJS']
pronoun_list=['PRP','PRP$']
wh_determiner_list=['WDT']
wh_pronoun_list=['WP']
wh_adverb_list=['WRB']
age="Iam a new born baby"
casualreplay=["i didn't understand that"]
time_list=['day','date','time','week','month','year']
